import "dotenv/config"

import { db } from "@/db/db"
import { currencies } from "@/db/schema"

type CurrencyInsert = typeof currencies.$inferInsert

const currencySeed: CurrencyInsert[] = [
	{ name: "United Arab Emirates Dirham", isoCode: "AED", symbol: "د.إ", position: "before" },
	{ name: "Afghan Afghani", isoCode: "AFN", symbol: "؋", position: "before" },
	{ name: "Albanian Lek", isoCode: "ALL", symbol: "L", position: "before" },
	{ name: "Armenian Dram", isoCode: "AMD", symbol: "֏", position: "before" },
	{ name: "Netherlands Antillean Guilder", isoCode: "ANG", symbol: "ƒ", position: "before" },
	{ name: "Angolan Kwanza", isoCode: "AOA", symbol: "Kz", position: "after" },
	{ name: "Argentine Peso", isoCode: "ARS", symbol: "AR$", position: "before" },
	{ name: "Australian Dollar", isoCode: "AUD", symbol: "A$", position: "before" },
	{ name: "Aruban Florin", isoCode: "AWG", symbol: "Aƒ", position: "before" },
	{ name: "Azerbaijani Manat", isoCode: "AZN", symbol: "₼", position: "before" },
	{
		name: "Bosnia and Herzegovina Convertible Mark",
		isoCode: "BAM",
		symbol: "KM",
		position: "after",
	},
	{ name: "Barbados Dollar", isoCode: "BBD", symbol: "Bds$", position: "before" },
	{ name: "Bangladeshi Taka", isoCode: "BDT", symbol: "৳", position: "before" },
	{ name: "Bulgarian Lev", isoCode: "BGN", symbol: "лв", position: "after" },
	{ name: "Bahraini Dinar", isoCode: "BHD", symbol: "د.ب", position: "before" },
	{ name: "Burundian Franc", isoCode: "BIF", symbol: "FBu", position: "after" },
	{ name: "Bermudian Dollar", isoCode: "BMD", symbol: "BD$", position: "before" },
	{ name: "Brunei Dollar", isoCode: "BND", symbol: "B$", position: "before" },
	{ name: "Bolivian Boliviano", isoCode: "BOB", symbol: "Bs.", position: "before" },
	{ name: "Brazilian Real", isoCode: "BRL", symbol: "R$", position: "before" },
	{ name: "Bahamian Dollar", isoCode: "BSD", symbol: "B$", position: "before" },
	{ name: "Bhutanese Ngultrum", isoCode: "BTN", symbol: "Nu.", position: "before" },
	{ name: "Botswana Pula", isoCode: "BWP", symbol: "P", position: "before" },
	{ name: "Belarusian Ruble", isoCode: "BYN", symbol: "Br", position: "after" },
	{ name: "Belize Dollar", isoCode: "BZD", symbol: "BZ$", position: "before" },
	{ name: "Canadian Dollar", isoCode: "CAD", symbol: "C$", position: "before" },
	{ name: "Congolese Franc", isoCode: "CDF", symbol: "FC", position: "after" },
	{ name: "Swiss Franc", isoCode: "CHF", symbol: "CHF", position: "before" },
	{ name: "Chilean Peso", isoCode: "CLP", symbol: "CLP$", position: "before" },
	{ name: "Chinese Yuan", isoCode: "CNY", symbol: "¥", position: "before" },
	{ name: "Colombian Peso", isoCode: "COP", symbol: "COL$", position: "before" },
	{ name: "Costa Rican Colón", isoCode: "CRC", symbol: "₡", position: "before" },
	{ name: "Cuban Peso", isoCode: "CUP", symbol: "CUP$", position: "before" },
	{ name: "Cape Verdean Escudo", isoCode: "CVE", symbol: "Esc", position: "after" },
	{ name: "Czech Koruna", isoCode: "CZK", symbol: "Kč", position: "after" },
	{ name: "Djiboutian Franc", isoCode: "DJF", symbol: "Fdj", position: "after" },
	{ name: "Danish Krone", isoCode: "DKK", symbol: "kr", position: "after" },
	{ name: "Dominican Peso", isoCode: "DOP", symbol: "RD$", position: "before" },
	{ name: "Algerian Dinar", isoCode: "DZD", symbol: "د.ج", position: "before" },
	{ name: "Egyptian Pound", isoCode: "EGP", symbol: "E£", position: "before" },
	{ name: "Eritrean Nakfa", isoCode: "ERN", symbol: "Nkf", position: "after" },
	{ name: "Ethiopian Birr", isoCode: "ETB", symbol: "Br", position: "after" },
	{ name: "Euro", isoCode: "EUR", symbol: "€", position: "before" },
	{ name: "Fijian Dollar", isoCode: "FJD", symbol: "FJ$", position: "before" },
	{ name: "Falkland Islands Pound", isoCode: "FKP", symbol: "£", position: "before" },
	{ name: "British Pound Sterling", isoCode: "GBP", symbol: "£", position: "before" },
	{ name: "Georgian Lari", isoCode: "GEL", symbol: "₾", position: "before" },
	{ name: "Guernsey Pound", isoCode: "GGP", symbol: "£", position: "before" },
	{ name: "Ghanaian Cedi", isoCode: "GHS", symbol: "GH₵", position: "before" },
	{ name: "Gibraltar Pound", isoCode: "GIP", symbol: "£", position: "before" },
	{ name: "Gambian Dalasi", isoCode: "GMD", symbol: "D", position: "before" },
	{ name: "Guinean Franc", isoCode: "GNF", symbol: "FG", position: "after" },
	{ name: "Guatemalan Quetzal", isoCode: "GTQ", symbol: "Q", position: "before" },
	{ name: "Guyanese Dollar", isoCode: "GYD", symbol: "GY$", position: "before" },
	{ name: "Hong Kong Dollar", isoCode: "HKD", symbol: "HK$", position: "before" },
	{ name: "Honduran Lempira", isoCode: "HNL", symbol: "L", position: "before" },
	{ name: "Haitian Gourde", isoCode: "HTG", symbol: "G", position: "after" },
	{ name: "Hungarian Forint", isoCode: "HUF", symbol: "Ft", position: "after" },
	{ name: "Indonesian Rupiah", isoCode: "IDR", symbol: "Rp", position: "before" },
	{ name: "Israeli New Shekel", isoCode: "ILS", symbol: "₪", position: "before" },
	{ name: "Isle of Man Pound", isoCode: "IMP", symbol: "£", position: "before" },
	{ name: "Indian Rupee", isoCode: "INR", symbol: "₹", position: "before" },
	{ name: "Iraqi Dinar", isoCode: "IQD", symbol: "د.ع", position: "before" },
	{ name: "Iranian Rial", isoCode: "IRR", symbol: "﷼", position: "before" },
	{ name: "Icelandic Króna", isoCode: "ISK", symbol: "kr", position: "after" },
	{ name: "Jersey Pound", isoCode: "JEP", symbol: "£", position: "before" },
	{ name: "Jamaican Dollar", isoCode: "JMD", symbol: "J$", position: "before" },
	{ name: "Jordanian Dinar", isoCode: "JOD", symbol: "د.ا", position: "before" },
	{ name: "Japanese Yen", isoCode: "JPY", symbol: "¥", position: "before" },
	{ name: "Kenyan Shilling", isoCode: "KES", symbol: "KSh", position: "before" },
	{ name: "Kyrgyzstani Som", isoCode: "KGS", symbol: "som", position: "after" },
	{ name: "Cambodian Riel", isoCode: "KHR", symbol: "៛", position: "before" },
	{ name: "Comorian Franc", isoCode: "KMF", symbol: "CF", position: "after" },
	{ name: "North Korean Won", isoCode: "KPW", symbol: "₩", position: "before" },
	{ name: "South Korean Won", isoCode: "KRW", symbol: "₩", position: "before" },
	{ name: "Kuwaiti Dinar", isoCode: "KWD", symbol: "د.ك", position: "before" },
	{ name: "Cayman Islands Dollar", isoCode: "KYD", symbol: "CI$", position: "before" },
	{ name: "Kazakhstani Tenge", isoCode: "KZT", symbol: "₸", position: "before" },
	{ name: "Lao Kip", isoCode: "LAK", symbol: "₭", position: "after" },
	{ name: "Lebanese Pound", isoCode: "LBP", symbol: "ل.ل", position: "before" },
	{ name: "Sri Lankan Rupee", isoCode: "LKR", symbol: "Rs", position: "before" },
	{ name: "Liberian Dollar", isoCode: "LRD", symbol: "L$", position: "before" },
	{ name: "Lesotho Loti", isoCode: "LSL", symbol: "L", position: "before" },
	{ name: "Libyan Dinar", isoCode: "LYD", symbol: "ل.د", position: "before" },
	{ name: "Moroccan Dirham", isoCode: "MAD", symbol: "د.م.", position: "before" },
	{ name: "Moldovan Leu", isoCode: "MDL", symbol: "L", position: "after" },
	{ name: "Malagasy Ariary", isoCode: "MGA", symbol: "Ar", position: "before" },
	{ name: "North Macedonian Denar", isoCode: "MKD", symbol: "ден", position: "after" },
	{ name: "Myanmar Kyat", isoCode: "MMK", symbol: "K", position: "before" },
	{ name: "Mongolian Tögrög", isoCode: "MNT", symbol: "₮", position: "before" },
	{ name: "Macanese Pataca", isoCode: "MOP", symbol: "MOP$", position: "before" },
	{ name: "Mauritanian Ouguiya", isoCode: "MRU", symbol: "UM", position: "after" },
	{ name: "Mauritian Rupee", isoCode: "MUR", symbol: "Rs", position: "before" },
	{ name: "Maldivian Rufiyaa", isoCode: "MVR", symbol: "Rf", position: "before" },
	{ name: "Malawian Kwacha", isoCode: "MWK", symbol: "MK", position: "before" },
	{ name: "Mexican Peso", isoCode: "MXN", symbol: "MX$", position: "before" },
	{ name: "Malaysian Ringgit", isoCode: "MYR", symbol: "RM", position: "before" },
	{ name: "Mozambican Metical", isoCode: "MZN", symbol: "MT", position: "before" },
	{ name: "Namibian Dollar", isoCode: "NAD", symbol: "N$", position: "before" },
	{ name: "Nigerian Naira", isoCode: "NGN", symbol: "₦", position: "before" },
	{ name: "Nicaraguan Córdoba", isoCode: "NIO", symbol: "C$", position: "before" },
	{ name: "Norwegian Krone", isoCode: "NOK", symbol: "kr", position: "after" },
	{ name: "Nepalese Rupee", isoCode: "NPR", symbol: "Rs", position: "before" },
	{ name: "New Zealand Dollar", isoCode: "NZD", symbol: "NZ$", position: "before" },
	{ name: "Omani Rial", isoCode: "OMR", symbol: "ر.ع.", position: "before" },
	{ name: "Panamanian Balboa", isoCode: "PAB", symbol: "B/.", position: "before" },
	{ name: "Peruvian Sol", isoCode: "PEN", symbol: "S/.", position: "before" },
	{ name: "Papua New Guinean Kina", isoCode: "PGK", symbol: "K", position: "before" },
	{ name: "Philippine Peso", isoCode: "PHP", symbol: "₱", position: "before" },
	{ name: "Pakistani Rupee", isoCode: "PKR", symbol: "Rs", position: "before" },
	{ name: "Polish Złoty", isoCode: "PLN", symbol: "zł", position: "after" },
	{ name: "Paraguayan Guaraní", isoCode: "PYG", symbol: "₲", position: "before" },
	{ name: "Qatari Riyal", isoCode: "QAR", symbol: "ر.ق", position: "before" },
	{ name: "Romanian Leu", isoCode: "RON", symbol: "lei", position: "after" },
	{ name: "Serbian Dinar", isoCode: "RSD", symbol: "дин.", position: "after" },
	{ name: "Russian Ruble", isoCode: "RUB", symbol: "₽", position: "before" },
	{ name: "Rwandan Franc", isoCode: "RWF", symbol: "FRw", position: "after" },
	{ name: "Saudi Riyal", isoCode: "SAR", symbol: "ر.س", position: "before" },
	{ name: "Solomon Islands Dollar", isoCode: "SBD", symbol: "SI$", position: "before" },
	{ name: "Seychellois Rupee", isoCode: "SCR", symbol: "Rs", position: "before" },
	{ name: "Sudanese Pound", isoCode: "SDG", symbol: "ج.س.", position: "before" },
	{ name: "Swedish Krona", isoCode: "SEK", symbol: "kr", position: "after" },
	{ name: "Singapore Dollar", isoCode: "SGD", symbol: "S$", position: "before" },
	{ name: "Saint Helena Pound", isoCode: "SHP", symbol: "£", position: "before" },
	{ name: "Sierra Leonean Leone", isoCode: "SLE", symbol: "Le", position: "after" },
	{ name: "Somali Shilling", isoCode: "SOS", symbol: "Sh", position: "before" },
	{ name: "Surinamese Dollar", isoCode: "SRD", symbol: "SR$", position: "before" },
	{ name: "South Sudanese Pound", isoCode: "SSP", symbol: "SS£", position: "before" },
	{ name: "São Tomé and Príncipe Dobra", isoCode: "STN", symbol: "Db", position: "before" },
	{ name: "Salvadoran Colón", isoCode: "SVC", symbol: "₡", position: "before" },
	{ name: "Syrian Pound", isoCode: "SYP", symbol: "£S", position: "before" },
	{ name: "Eswatini Lilangeni", isoCode: "SZL", symbol: "E", position: "before" },
	{ name: "Thai Baht", isoCode: "THB", symbol: "฿", position: "before" },
	{ name: "Tajikistani Somoni", isoCode: "TJS", symbol: "SM", position: "after" },
	{ name: "Turkmenistani Manat", isoCode: "TMT", symbol: "m", position: "after" },
	{ name: "Tunisian Dinar", isoCode: "TND", symbol: "د.ت", position: "before" },
	{ name: "Tongan Paʻanga", isoCode: "TOP", symbol: "T$", position: "before" },
	{ name: "Turkish Lira", isoCode: "TRY", symbol: "₺", position: "before" },
	{ name: "Trinidad and Tobago Dollar", isoCode: "TTD", symbol: "TT$", position: "before" },
	{ name: "New Taiwan Dollar", isoCode: "TWD", symbol: "NT$", position: "before" },
	{ name: "Tanzanian Shilling", isoCode: "TZS", symbol: "TSh", position: "before" },
	{ name: "Ukrainian Hryvnia", isoCode: "UAH", symbol: "₴", position: "before" },
	{ name: "Ugandan Shilling", isoCode: "UGX", symbol: "USh", position: "before" },
	{ name: "United States Dollar", isoCode: "USD", symbol: "$", position: "before" },
	{ name: "United States Dollar (Next day)", isoCode: "USN", symbol: "$", position: "before" },
	{ name: "Uruguayan Peso", isoCode: "UYU", symbol: "UY$", position: "before" },
	{ name: "Uzbekistani So'm", isoCode: "UZS", symbol: "so'm", position: "after" },
	{ name: "Venezuelan Bolívar Soberano", isoCode: "VES", symbol: "Bs.", position: "before" },
	{ name: "Vietnamese Đồng", isoCode: "VND", symbol: "₫", position: "after" },
	{ name: "Vanuatu Vatu", isoCode: "VUV", symbol: "Vt", position: "after" },
	{ name: "Samoan Tala", isoCode: "WST", symbol: "WS$", position: "before" },
	{ name: "Central African CFA Franc", isoCode: "XAF", symbol: "FCFA", position: "after" },
	{ name: "East Caribbean Dollar", isoCode: "XCD", symbol: "EC$", position: "before" },
	{ name: "West African CFA Franc", isoCode: "XOF", symbol: "CFA", position: "after" },
	{ name: "CFP Franc", isoCode: "XPF", symbol: "₣", position: "after" },
	{ name: "Yemeni Rial", isoCode: "YER", symbol: "﷼", position: "before" },
	{ name: "South African Rand", isoCode: "ZAR", symbol: "R", position: "before" },
	{ name: "Zambian Kwacha", isoCode: "ZMW", symbol: "ZK", position: "before" },
	{ name: "Zimbabwean Dollar", isoCode: "ZWL", symbol: "Z$", position: "before" },
]

async function main() {
	await db.insert(currencies).values(currencySeed).onConflictDoNothing({
		target: currencies.isoCode,
	})

	console.log(`Seeded ${currencySeed.length} currencies`)
}

main()
	.then(() => process.exit(0))
	.catch((error) => {
		console.error(error)
		process.exit(1)
	})
